version: 2.1

orbs:
  discord: antonioned/discord@0.1.0

jobs:
  build:
    docker:
      - image: circleci/elixir:1.13-node
        environment:
          MIX_ENV: test
          MIX_TEST_DB_HOST: localhost

      - image: circleci/postgres:9.6
        environment:
          POSTGRES_USER: postgres
          POSTGRES_DB: demo_test
          POSTGRES_PASSWORD: postgres

    working_directory: ~/app

    steps:
      - checkout
      - run: mix local.hex --force
      - run: mix local.rebar --force
      - run: mix archive.install --force hex phx_new
      - run: mix do deps.get, compile
      - run: mix credo
      - run: mix test
      - run: mix dialyzer

      - discord/status:
          failure_message: "**${CIRCLE_USERNAME}**'s: **${CIRCLE_JOB}** failed."
          success_message: "**${CIRCLE_USERNAME}** success."